# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-02 22:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0004_auto_20180302_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='courseid',
        ),
    ]
